spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/Librarydb
    username: postgres
    password: 1111
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: false
    clear-checksums: true
logging:
  level:
    liquibase: DEBUG